### PR TITLE
Brand page

### PR DESCRIPTION
**Pull request by mmcc**
I really wish I'd just made a public Notion doc and shared this >_<*

Also, we should make a home page card for the homepage for Europe ticket sales 👍

### CODE REVIEW

**Comment by mmcc** [comment]
Also, pretty sure we landed on "brand-guidelines", but also fine with just "brand"

**Comment by GeneticGenesis** [comment]
Haha, we actually settled on `brand-guide` (I wrote it down at the time)

I've updated the hero in #27, which I'll also merge alongside this once I've review it.

**Comment by GeneticGenesis** [comment]
This looks great to me.

The only addition I would make is that we should also specify that you're expected to use _only_ the logo for the event that you're sponsoring, IE, use the Demuxed Europe logo if you're sponsoring Demuxed Europe.

**Comment by GeneticGenesis** [comment]
Merging this so the page exists, and we can iterate on my comments above.

**Pull request merged**
